### ISSUE TITLE
Membership Hack

### ISSUE THREAD

**Issue by fwij** [rxzyx/prodigy-hack#11]
It shows the badge, but it doesnt give me the perks.

**Comment by fwij** [comment]
doesnt save as well + i cant rune run or player battle, 
![image](https://user-images.githubusercontent.com/87453177/168604633-55c2adbe-dd5b-41fd-bb1d-25096843319b.png)

**Comment by rxzyx** [comment]
Weird, what level are you?

**Comment by fwij** [comment]
I'm at level 56.

**Comment by fwij** [comment]
nope, this is my first one

**Comment by rxzyx** [comment]
What level of the pets did you set them to?
What amount of weapons did you input for add items, and also what was the amount of currency you inputed?

**Comment by fwij** [comment]
pets were level 60
weapons - 1
amount of currency - 999

**Comment by rxzyx** [comment]
When you refresh, do you still encounter the problem where you can’t join a game?

**Comment by fwij** [comment]
yes, i do.

**Comment by rxzyx** [comment]
It may be because you set the pet level higher than your level, try setting the pets to like level 58 or something.

**Comment by fwij** [comment]
just tried that, not working

**Comment by rxzyx** [comment]
Try removing the mythics (switch to a different random pet)

**Comment by fwij** [comment]
it worked, ty!

**Comment by rxzyx** [comment]
Np!
