### ISSUE TITLE
It does not seem I can reset my account. Is it supposed to do anything else???

### ISSUE THREAD

**Issue by NordaySheniki** [rxzyx/prodigy-hack#15]
After trying around 3 times, the account reset kept giving me the same no response. While in Lamplight Town, it gave the 418 Error Code.

**Comment by rxzyx** [comment]
That’s because you’re using other hacks with it, try using it on it’s own.

**Comment by rxzyx** [comment]
Did you click "OK"?

**Comment by NordaySheniki** [comment]
yes.

**Comment by rxzyx** [comment]
I think with Prodigy's new "anti-cheat" they accidentally made it so it will ignore statements if you have absolutely nothing.

**Comment by NordaySheniki** [comment]
oh.

**Comment by NordaySheniki** [comment]
they really gotta get the reset account option in the game.

**Comment by rxzyx** [comment]
Yes let me try to replicate the reset, I will let you know how I do.

**Comment by rxzyx** [comment]
Fixed

**Comment by NordaySheniki** [comment]
k
