### ISSUE TITLE
X loader hacks

### ISSUE THREAD

**Issue by ShorterCat194** [rxzyx/prodigy-hack#166]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Slept66** [comment]
I tried it before, and it did work for few months after that I was not able to enter prodigy due to a bug it had, and it still has the same bug.

This is way better because, it looks way less risky and it's trustable.

**Comment by ShorterCat194** [comment]
It works but sometimes you cant log in to prodigy. its annoying

**Comment by ShorterCat194** [comment]
Hello Welcome To My Hack Site!! Copy This Then your hacks will work!! Select Chrome Web Store X Loader. 
CODE: funcion: https://admin.google.com/ServiceNotAllowed?application=865579354872&pli=1
