### ISSUE TITLE
Pets not having right moves, They all have snowling ball and forests hurricane, I want the defaut moves on them :(

### ISSUE THREAD

**Issue by soulcattah** [rxzyx/prodigy-hack#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rxzyx** [comment]
They were added to ensure the “unlock” element but I guess by tomorrow I’ll add a separate one without the effects.
