### ISSUE TITLE
Damage hack doesn't work

### ISSUE THREAD

**Issue by Bebahn** [rxzyx/prodigy-hack#21]
I was doing the "Defeat 5 Aquratiots" or something but when I used the code, the damage was just the normal damage 
![image](https://user-images.githubusercontent.com/108024449/175111914-f1e05054-9b77-4da5-8c59-ecb0cfad0f5e.png)

**Comment by Bebahn** [comment]
I did that but it still does normal damage

**Comment by rxzyx** [comment]
Hacks are for prodigy math game. Not English.

**Comment by Bebahn** [comment]
It is prodigy math tho
