### ISSUE TITLE
(please read me!) Dear rxyzx,

### ISSUE THREAD

**Issue by igenoxnos** [rxzyx/prodigy-hack#33]
Hi my name is liam I am 10yrs old and I love to code I have been finding hacks for games online and your the only one that makes them work! I love the work you do and i know it takes you a long time making these things and I just want to apreciate the work you do to make this stuff and the time and the effort and to say, thank you. thank you for making games more fun and your hacks have helped me out when im stuck and, the way do these things for these people you dont even know is amasing. and i dont know if i could ever do that! so thank you for everything you do! I dont know if anyone has told you how big of a heart you have helping these people, making stuff for them to help them, but you do! and even when its hard you still do it. so i just want to take this time in my day to say thank you. and I hope you have an amasing day with amasing people and never give up.
         
                        your biggest coder fan,
                                                              Liam

**Comment by igenoxnos** [comment]
wrong button

**Comment by rxzyx** [comment]
Thank you so much for the kind comment, Liam! I will continue to do the great hacks!

**Comment by igenoxnos** [comment]
:)

**Comment by igenoxnos** [comment]
your the best in the coding world!
