### ISSUE TITLE
um needed fix

### ISSUE THREAD

**Issue by prodigyisneededforhacks** [rxzyx/prodigy-hack#34]
when i tried out a hack it said VM347:1 Uncaught TypeError: Cannot read properties of undefined (reading 'prodigy')
    at <anonymous>:1:15
(anonymous) @ VM347:1 i dont know what that means? but i think u need to fix your coding just a friendly reminder

**Comment by rxzyx** [comment]
^

**Comment by prodigyisneededforhacks** [comment]
so sorry the hack i was inserting was in the wrong thing
