### ISSUE TITLE
None of the hacks are working

### ISSUE THREAD

**Issue by toxzwyd** [rxzyx/prodigy-hack#36]
I've been using these hacks  lot recently for my math class, and none of the hacks have been working for the past few days. I don't know why they aren't working, but I just wanted to let you know about it.

**Comment by tommyboiiiiii** [comment]
i know i use javascript: in my browser and the only thing that worked was the gold hack

**Comment by blooketgamer243** [comment]
Same for me

**Comment by rxzyx** [comment]
Use console. Also hacks will be checked again.

**Comment by tommyboiiiiii** [comment]
i cant use console
