### ISSUE TITLE
useless

### ISSUE THREAD

**Issue by nightclubs** [rxzyx/prodigy-hack#37]
There are literal extensions that are 90x better than this with full GUI's and everything that help the user navigate around, so there is no need to create a new extension for each hack.

**Comment by rxzyx** [comment]
I am so sorry that you are jealous of the hacks! Please don’t come back ))

**Comment by nightclubs** [comment]
> I am so sorry that you are jealous of the hacks! Please don’t come back ))

jealous? I do not need to be jealous of prodigy hacks.
