### ISSUE TITLE
Fully unlocking epics for unlockpets.js and fixing level hack for changelevel.js

### ISSUE THREAD

**Issue by qwrdf** [rxzyx/prodigy-hack#5]
Missing parts
For unlocking all pets, it doesn't fully unlock epics. You can use them, but you cannot do the battles in the Epics area. For the level hack, after a team titan battle, it shows your real level.

Suggestion for unlockpets.js
Maybe add Mythical Epics?

**Comment by rxzyx** [comment]
Yes I am aware that the pack hack doesn’t do that but the level hack is supposed to reload the page so then it saves the level, let me fix that now.

**Comment by rxzyx** [comment]
Ok I don’t see a problem with the level hack so I’ll look at it later but yeah I’ll look into the mythical pet idea

**Comment by rxzyx** [comment]
I did the mythical hack i’m releasing in a bit if I don’t find any bugs

**Comment by rxzyx** [comment]
Added your request.

**Comment by kjimel290-collab** [comment]
hey rxzyx how do i get the rest of the mythical epics i dont have
