### ISSUE TITLE
You Can't Save Your Items After Using Script

### ISSUE THREAD

**Issue by natnicharris** [rxzyx/prodigy-hack#62]
My request is related to the fact that you can not save your items after refreshing. Unlike the player pet hacking script which alternates your game play forever. 

I would most definitely appreciate a possible change in the script, similar to the pet hack you created, or a possible way I could make your program work forever.

Consider adding the item and currency, to the pet hack to make it continue forever in the account.

**Comment by 2sus2uy** [comment]
your right there is no way you can do that natnicharris is a retarded idiot.

**Comment by natnicharris** [comment]
I had mentioned that it was possible to save your data with the pets, so I
was wondering if it is possible you could do the same with items. I am only
doing this for my son anyway, and I have a bachelors and a masters degree
in programming, I am not that old and dumb.

**Comment by natnicharris** [comment]
> your right there is no way you can do that natnicharris is a retarded idiot.

Perhaps you should use a comma.

**Comment by natnicharris** [comment]
"I am only doing this for my son anyway"

**Comment by natnicharris** [comment]
I literally program in JavaScript, I understand these programs, and I even
told my son that I did not think that prodigy would save the hack, but he
told me to write it anyway. I am not really interested in hacking prodigy
or any school learning games, just give me a break alr.

**Comment by MVSuiteDev** [comment]
wow ur cheating for your son
ERROR 418

**Comment by rxzyx** [comment]
Hello! This would result in an overflow which would cause `Prodigy` to detect an unusual occurance and cause it to return error 418, thank you :)
