### ISSUE TITLE
I don’t know how to use it

### ISSUE THREAD

**Issue by Pikapipokemon** [rxzyx/prodigy-hack#70]
It’s self explanatory. I have no idea how this works

**Comment by noimno** [comment]
ok i will tell you

**Comment by noimno** [comment]
but dont use email mostly dont check it

**Comment by noimno** [comment]
50$

**Comment by noimno** [comment]
wait its probably night for you...

**Comment by Pikapipokemon** [comment]
Plz tell me I want free membership

**Comment by Pikapipokemon** [comment]
Sorry about the closing and reopening. I am so confused about how to use github. Cause I joined a few days ago

**Comment by noimno** [comment]
sorry was at school and you sent that 13 hours ago but i will still tell you

**Comment by noimno** [comment]
well the just ignore it was at 9: something

**Comment by noimno** [comment]
step 1  go to prodigy and join any world
step 2  once you loaded in either do ctrl shift i or go to your bookmark if you do bookmark put javascript: then the code or if you do ctrl shift i just go to console and paste in the code
finish then you got what you needed but the free membership is temporary meaning when you log out you dont have membership

**Comment by noimno** [comment]
well you can do it with any hacks but you have to copy the code that you want then do the steps thing i should have done step 2 as go on github go to prodigy hacks click on the best hack which is rxzyx just its the only one that works then go to player click on what hack you need the click the 2 squares then do the rest that i commented

**Comment by noimno** [comment]
and im telling you this because by the time your reading this im at school go from 8:15 to 2:15 boring 6 hours

**Comment by noimno** [comment]
pain

**Comment by Pikapipokemon** [comment]
I know

**Comment by Pikapipokemon** [comment]
But I have iPad

**Comment by Pikapipokemon** [comment]
No pc

**Comment by noimno** [comment]
oh

**Comment by noimno** [comment]
yeah just do step 1 and 2 but the url part on step 2 try that

**Comment by noimno** [comment]
which is javascript: then the code or hack you want

**Comment by Pikapipokemon** [comment]
I tried that

**Comment by Pikapipokemon** [comment]
Bro I have 8 hours of school

**Comment by Pikapipokemon** [comment]
Rip me

**Comment by noimno** [comment]
i know painful

**Comment by noimno** [comment]
like whats the point for long hours we are not gonna become Einstein the more ours we have of school

**Comment by noimno** [comment]
what time is it for you for me its 3:02 AM

**Comment by noimno** [comment]
![th](https://user-images.githubusercontent.com/99223701/234199477-bab6dd65-093b-42e9-9a39-73a176a34744.jpg)

**Comment by Pikapipokemon** [comment]
I have to go

**Comment by noimno** [comment]
ok bye

**Comment by Pikapipokemon** [comment]
I’m busy

**Comment by noimno** [comment]
ok

**Comment by noimno** [comment]
i have a feeling the ghosts here
![th](https://user-images.githubusercontent.com/99223701/234200458-627d3ba4-2b42-46e7-bc4f-5a34dadf122a.jpg)

**Comment by Pikapipokemon** [comment]
So do I copy the code?

**Comment by Pikapipokemon** [comment]
Cause I did that

**Comment by noimno** [comment]
you copy then paste it

**Comment by Pikapipokemon** [comment]
Ah

**Comment by noimno** [comment]
ok see if it works

**Comment by Pikapipokemon** [comment]
:(

**Comment by noimno** [comment]
oh

**Comment by noimno** [comment]
ima show you a screen shot of what iy looks like

**Comment by Pikapipokemon** [comment]
Nonsense

**Comment by Pikapipokemon** [comment]
Ok

**Comment by noimno** [comment]
forgot how to take a screen shot bruhhhhh

**Comment by Pikapipokemon** [comment]
Huh

**Comment by Pikapipokemon** [comment]
Bruh

**Comment by Pikapipokemon** [comment]
Ok

**Comment by Pikapipokemon** [comment]
It’s like 11 26 am here

**Comment by noimno** [comment]
its 3:27 AM

**Comment by Pikapipokemon** [comment]
I have school ☹️☹️☹️☹️☹️

**Comment by noimno** [comment]
sameeee

**Comment by noimno** [comment]
got the screenshot

**Comment by noimno** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/99223701/234205875-8ec525c8-958e-4406-9a25-fd30968e9ece.png)

**Comment by Pikapipokemon** [comment]
Like I am in school

**Comment by Pikapipokemon** [comment]
In the building itself

**Comment by Pikapipokemon** [comment]
Yes

**Comment by noimno** [comment]
focus

**Comment by noimno** [comment]
![Screenshot 2023-04-25 033314](https://user-images.githubusercontent.com/99223701/234206693-a000db42-91fe-4548-ac7f-18fc098ce959.png)

**Comment by noimno** [comment]
thats what you put in url bar

**Comment by noimno** [comment]
then paste the code you want

**Comment by Pikapipokemon** [comment]
Aha

**Comment by noimno** [comment]
dont mind the blue dont know what happened

**Comment by Pikapipokemon** [comment]
Same thing…

**Comment by Pikapipokemon** [comment]
Lunch time

**Comment by noimno** [comment]
ok bye

**Comment by Pikapipokemon** [comment]
Get some rest bro

**Comment by noimno** [comment]
not tired

**Comment by noimno** [comment]
probably gonna sleep at 7 but ima try at 5 for me

**Comment by noimno** [comment]
right now 3:41

**Comment by noimno** [comment]
![flat,1000x1000,075,f](https://user-images.githubusercontent.com/99223701/234208939-48ed459d-c096-4aca-869f-1acf45179bca.jpg)

**Comment by noimno** [comment]
ima sleep its 4:09

**Comment by noimno** [comment]
best sleep ever

**Comment by noimno** [comment]
POV me: 
![flat,1000x1000,075,f](https://user-images.githubusercontent.com/99223701/234398765-d709d647-47d3-4236-aed7-960cec618533.jpg)

**Comment by noimno** [comment]
4:42 pm for me

**Comment by Pikapipokemon** [comment]
Bro

**Comment by Pikapipokemon** [comment]
You told me that at 12 30 for me

**Comment by Pikapipokemon** [comment]
Am

**Comment by noimno** [comment]
oh

**Comment by noimno** [comment]
what time is it for you?

**Comment by noimno** [comment]
for me its 1:19

**Comment by noimno** [comment]
am

**Comment by noimno** [comment]
hello?

**Comment by noimno** [comment]
oh wait your in school...

**Comment by Pikapipokemon** [comment]
It works

**Comment by Pikapipokemon** [comment]
There was just a small space

**Comment by Pikapipokemon** [comment]
Yay

**Comment by noimno** [comment]
nice

**Comment by noimno** [comment]
you closed this as completed

**Comment by noimno** [comment]
well, Ima help other people if they even reply.

**Comment by noimno** [comment]
bye

**Comment by noimno** [comment]
ima sleep ![Uploading flat,1000x1000,075,f.jpg…]()

**Comment by noimno** [comment]
ima sleep
![Uploading flat,1000x1000,075,f.jpg…]()

**Comment by noimno** [comment]
ima sleep

**Comment by noimno** [comment]
wow 100 comments most of it is me talking to myself nice

**Comment by Pikapipokemon** [comment]
Bruh I’m in class

**Comment by noimno** [comment]
i konw

**Comment by noimno** [comment]
think its like 1 something pm think you were taking building?

**Comment by noimno** [comment]
i think not yet

**Comment by noimno** [comment]
yeah ima sleep so tired i got tears coming out of my eyes

**Comment by noimno** [comment]
im so lonely 💀

**Comment by noimno** [comment]
make sure to not get caught doing the hacks
