### ISSUE TITLE
glitch where you cant buy anything

### ISSUE THREAD

**Issue by ttvkilier** [rxzyx/prodigy-hack#9]
i cant buy anything expect the potions in Lamplight Town

**Comment by rxzyx** [comment]
What does it say? Like you can't buy or just nothing

**Comment by rxzyx** [comment]
Works fine for me? I'll tell you if I find anything.

**Comment by ttvkilier** [comment]
it does let me click it but i cant buy it even with the currency needed

**Comment by rxzyx** [comment]
I think it's because the item is already owned, but a different value has other data, idk

**Comment by ttvkilier** [comment]
i did not have it owned

**Comment by rxzyx** [comment]
Hm so then I'm not sure

**Comment by ttvkilier** [comment]
okay i will comment if i find out but the only clue i have is that it might be the membership

**Comment by rxzyx** [comment]
Membership is on the client, so probably not

**Comment by ttvkilier** [comment]
okay
